version: '2'
linters:
  enable:
    - gosec
    - govet
    - staticcheck
  disable:
    - unused # Had to add this because we are not running linter on _test files and linter thinks that some func's are unused