// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	pubsubx "github.com/clinia/x/pubsubx"
	mock "github.com/stretchr/testify/mock"
)

// PubSubOption is an autogenerated mock type for the PubSubOption type
type PubSubOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *PubSubOption) Execute(_a0 *pubsubx.PubSubOptions) {
	_m.Called(_a0)
}

// NewPubSubOption creates a new instance of PubSubOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPubSubOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *PubSubOption {
	mock := &PubSubOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
